-- GENERATED by tool/gen_display_name_sql.dart -- DO NOT EDIT.
-- Source of truth: test/fixtures/display_names.json
--
-- Asserts that ingredient_display_name() in Postgres agrees
-- with DisplayNameChain in Dart on every fixture case (D72).
-- Raises on the first disagreement.
--
-- Run: make test-sql

do $$
declare
  test_id  uuid;
  actual   text;
  failures int := 0;
begin
  -- requested locale's display name wins over another locale's display name
  insert into ingredients default values
  returning id into test_id;
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn flour c1', 'en', true, 'curated', '2020-01-01T00:00:00Z'::timestamptz);
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn brašno c1', 'sr', true, 'curated', '2020-01-02T00:00:00Z'::timestamptz);
  select ingredient_display_name(test_id, 'sr') into actual;
  if actual is distinct from 'Zdn brašno c1' then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'requested locale''s display name wins over another locale''s display name', actual, 'Zdn brašno c1';
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  -- any locale's display name beats the requested locale's non-display name
  insert into ingredients default values
  returning id into test_id;
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn šargarepa stari naziv c2', 'sr', false, 'curated', '2020-01-01T00:00:00Z'::timestamptz);
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn carrot c2', 'en', true, 'curated', '2020-01-02T00:00:00Z'::timestamptz);
  select ingredient_display_name(test_id, 'sr') into actual;
  if actual is distinct from 'Zdn carrot c2' then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'any locale''s display name beats the requested locale''s non-display name', actual, 'Zdn carrot c2';
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  -- with no display name at all, the requested locale wins on locale alone
  insert into ingredients default values
  returning id into test_id;
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn flour c3', 'en', false, 'curated', '2020-01-01T00:00:00Z'::timestamptz);
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn brašno alias c3', 'sr', false, 'curated', '2020-01-02T00:00:00Z'::timestamptz);
  select ingredient_display_name(test_id, 'sr') into actual;
  if actual is distinct from 'Zdn brašno alias c3' then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'with no display name at all, the requested locale wins on locale alone', actual, 'Zdn brašno alias c3';
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  -- everything else tied, the oldest name wins
  insert into ingredients default values
  returning id into test_id;
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn second alias c4', 'sr', false, 'curated', '2020-06-01T00:00:00Z'::timestamptz);
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn first alias c4', 'sr', false, 'curated', '2020-01-01T00:00:00Z'::timestamptz);
  select ingredient_display_name(test_id, 'sr') into actual;
  if actual is distinct from 'Zdn first alias c4' then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'everything else tied, the oldest name wins', actual, 'Zdn first alias c4';
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  -- the requested locale has no rows at all, falls back to any display name
  insert into ingredients default values
  returning id into test_id;
  insert into ingredient_names
    (ingredient_id, name, locale, is_display_name, source, created_at)
  values
    (test_id, 'Zdn brašno c5', 'sr', true, 'curated', '2020-01-01T00:00:00Z'::timestamptz);
  select ingredient_display_name(test_id, 'en') into actual;
  if actual is distinct from 'Zdn brašno c5' then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'the requested locale has no rows at all, falls back to any display name', actual, 'Zdn brašno c5';
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  -- no names at all resolves to null, not an error
  insert into ingredients default values
  returning id into test_id;
  select ingredient_display_name(test_id, 'sr') into actual;
  if actual is distinct from null then
    failures := failures + 1;
    raise warning 'display_names: % -- got %, expected %',
      'no names at all resolves to null, not an error', actual, null;
  end if;
  delete from ingredient_names where ingredient_id = test_id;
  delete from ingredients where id = test_id;

  if failures > 0 then
    raise exception '% display-name case(s) failed. Postgres ingredient_display_name() and Dart DisplayNameChain disagree.', failures;
  end if;

  raise notice 'display_names: 6 case(s) passed';
end
$$;
