-- GENERATED by tool/gen_normalization_sql.dart -- DO NOT EDIT.
-- Source of truth: test/fixtures/normalization.json
--
-- Asserts that normalize_text() in Postgres agrees with
-- TextNormalizer in Dart on every fixture case. Raises on the
-- first disagreement.
--
-- Run: make test-sql

do $$
declare
  failures int := 0;
  actual   text;
begin
  actual := normalize_text('ćufte');
  if actual is distinct from 'cufte' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'ćufte', actual, 'cufte';
  end if;
  actual := normalize_text('Ćufte');
  if actual is distinct from 'cufte' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Ćufte', actual, 'cufte';
  end if;
  actual := normalize_text('ћуфте');
  if actual is distinct from 'cufte' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'ћуфте', actual, 'cufte';
  end if;
  actual := normalize_text('đuveč');
  if actual is distinct from 'djuvec' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'đuveč', actual, 'djuvec';
  end if;
  actual := normalize_text('djuveč');
  if actual is distinct from 'djuvec' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'djuveč', actual, 'djuvec';
  end if;
  actual := normalize_text('Đuveč');
  if actual is distinct from 'djuvec' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Đuveč', actual, 'djuvec';
  end if;
  actual := normalize_text('šargarepa');
  if actual is distinct from 'sargarepa' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'šargarepa', actual, 'sargarepa';
  end if;
  actual := normalize_text('Njegoš');
  if actual is distinct from 'njegos' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Njegoš', actual, 'njegos';
  end if;
  actual := normalize_text('  bela   pavlaka ');
  if actual is distinct from 'bela pavlaka' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      '  bela   pavlaka ', actual, 'bela pavlaka';
  end if;
  actual := normalize_text('ЖЕЛЕ');
  if actual is distinct from 'zele' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'ЖЕЛЕ', actual, 'zele';
  end if;
  actual := normalize_text('brašno, glatko');
  if actual is distinct from 'brasno, glatko' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'brašno, glatko', actual, 'brasno, glatko';
  end if;
  actual := normalize_text('Dž');
  if actual is distinct from 'dz' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Dž', actual, 'dz';
  end if;
  actual := normalize_text('Њ');
  if actual is distinct from 'nj' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Њ', actual, 'nj';
  end if;
  actual := normalize_text('ЏЕМ');
  if actual is distinct from 'dzem' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'ЏЕМ', actual, 'dzem';
  end if;
  actual := normalize_text('Љубав');
  if actual is distinct from 'ljubav' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Љубав', actual, 'ljubav';
  end if;
  actual := normalize_text('');
  if actual is distinct from '' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      '', actual, '';
  end if;
  actual := normalize_text('   ');
  if actual is distinct from '' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      '   ', actual, '';
  end if;
  actual := normalize_text('ђubre');
  if actual is distinct from 'djubre' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'ђubre', actual, 'djubre';
  end if;
  actual := normalize_text(E'mleko\tu\nprahu');
  if actual is distinct from 'mleko u prahu' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      E'mleko\tu\nprahu', actual, 'mleko u prahu';
  end if;
  actual := normalize_text('Пилећа džigerica');
  if actual is distinct from 'pileca dzigerica' then
    failures := failures + 1;
    raise warning 'normalize_text(%) = %, expected %',
      'Пилећа džigerica', actual, 'pileca dzigerica';
  end if;

  if failures > 0 then
    raise exception '% normalization case(s) failed. Postgres normalize_text() and Dart TextNormalizer disagree.', failures;
  end if;

  raise notice 'normalization: 20 case(s) passed';
end
$$;
