-- GENERATED by tool/gen_unit_alias_sql.dart -- DO NOT EDIT.
-- Source of truth: test/fixtures/unit_aliases.json
--
-- Asserts that every unit spelling the Dart line parser is
-- expected to recognise exists in unit_names and resolves to
-- exactly one unit. Two checks per alias: that the pair is
-- present, and that no OTHER unit also claims the spelling --
-- an alias meaning two things would have the parser silently
-- pick whichever row came back first.
--
-- Run: make test-sql

do $$
declare
  failures int := 0;
  other    text;
begin
  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('g')
                   and unit_code = 'g') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'g', 'g';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('g')
     and unit_code <> 'g' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'g', 'g', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('gr')
                   and unit_code = 'g') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'gr', 'g';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('gr')
     and unit_code <> 'g' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'gr', 'g', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('gram')
                   and unit_code = 'g') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'gram', 'g';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('gram')
     and unit_code <> 'g' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'gram', 'g', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('grama')
                   and unit_code = 'g') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'grama', 'g';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('grama')
     and unit_code <> 'g' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'grama', 'g', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('grams')
                   and unit_code = 'g') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'grams', 'g';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('grams')
     and unit_code <> 'g' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'grams', 'g', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kg')
                   and unit_code = 'kg') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kg', 'kg';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kg')
     and unit_code <> 'kg' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kg', 'kg', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kilogram')
                   and unit_code = 'kg') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kilogram', 'kg';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kilogram')
     and unit_code <> 'kg' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kilogram', 'kg', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kila')
                   and unit_code = 'kg') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kila', 'kg';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kila')
     and unit_code <> 'kg' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kila', 'kg', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('ml')
                   and unit_code = 'ml') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'ml', 'ml';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('ml')
     and unit_code <> 'ml' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'ml', 'ml', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('mililitar')
                   and unit_code = 'ml') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'mililitar', 'ml';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('mililitar')
     and unit_code <> 'ml' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'mililitar', 'ml', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('dl')
                   and unit_code = 'dl') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'dl', 'dl';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('dl')
     and unit_code <> 'dl' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'dl', 'dl', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('decilitar')
                   and unit_code = 'dl') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'decilitar', 'dl';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('decilitar')
     and unit_code <> 'dl' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'decilitar', 'dl', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('l')
                   and unit_code = 'l') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'l', 'l';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('l')
     and unit_code <> 'l' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'l', 'l', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('litar')
                   and unit_code = 'l') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'litar', 'l';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('litar')
     and unit_code <> 'l' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'litar', 'l', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('litre')
                   and unit_code = 'l') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'litre', 'l';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('litre')
     and unit_code <> 'l' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'litre', 'l', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašičica')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašičica', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašičica')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašičica', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašičice')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašičice', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašičice')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašičice', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašičicu')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašičicu', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašičicu')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašičicu', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čajna kašičica')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čajna kašičica', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čajna kašičica')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čajna kašičica', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('tsp')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'tsp', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('tsp')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'tsp', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('teaspoon')
                   and unit_code = 'tsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'teaspoon', 'tsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('teaspoon')
     and unit_code <> 'tsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'teaspoon', 'tsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašika')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašika', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašika')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašika', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašike')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašike', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašike')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašike', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kašiku')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kašiku', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kašiku')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kašiku', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('supena kašika')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'supena kašika', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('supena kašika')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'supena kašika', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kš')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kš', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kš')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kš', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('tbsp')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'tbsp', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('tbsp')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'tbsp', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('tablespoon')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'tablespoon', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('tablespoon')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'tablespoon', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('tablespoons')
                   and unit_code = 'tbsp') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'tablespoons', 'tbsp';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('tablespoons')
     and unit_code <> 'tbsp' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'tablespoons', 'tbsp', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('šolja')
                   and unit_code = 'cup') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'šolja', 'cup';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('šolja')
     and unit_code <> 'cup' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'šolja', 'cup', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('šolje')
                   and unit_code = 'cup') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'šolje', 'cup';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('šolje')
     and unit_code <> 'cup' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'šolje', 'cup', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('šolju')
                   and unit_code = 'cup') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'šolju', 'cup';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('šolju')
     and unit_code <> 'cup' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'šolju', 'cup', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('cup')
                   and unit_code = 'cup') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'cup', 'cup';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('cup')
     and unit_code <> 'cup' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'cup', 'cup', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('cups')
                   and unit_code = 'cup') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'cups', 'cup';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('cups')
     and unit_code <> 'cup' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'cups', 'cup', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čaša')
                   and unit_code = 'glass') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čaša', 'glass';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čaša')
     and unit_code <> 'glass' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čaša', 'glass', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čaše')
                   and unit_code = 'glass') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čaše', 'glass';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čaše')
     and unit_code <> 'glass' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čaše', 'glass', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('glass')
                   and unit_code = 'glass') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'glass', 'glass';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('glass')
     and unit_code <> 'glass' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'glass', 'glass', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kom')
                   and unit_code = 'kom') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kom', 'kom';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kom')
     and unit_code <> 'kom' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kom', 'kom', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('komad')
                   and unit_code = 'kom') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'komad', 'kom';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('komad')
     and unit_code <> 'kom' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'komad', 'kom', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('komada')
                   and unit_code = 'kom') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'komada', 'kom';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('komada')
     and unit_code <> 'kom' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'komada', 'kom', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('piece')
                   and unit_code = 'kom') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'piece', 'kom';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('piece')
     and unit_code <> 'kom' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'piece', 'kom', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('pieces')
                   and unit_code = 'kom') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'pieces', 'kom';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('pieces')
     and unit_code <> 'kom' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'pieces', 'kom', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čen')
                   and unit_code = 'clove') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čen', 'clove';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čen')
     and unit_code <> 'clove' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čen', 'clove', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čena')
                   and unit_code = 'clove') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čena', 'clove';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čena')
     and unit_code <> 'clove' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čena', 'clove', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('čenova')
                   and unit_code = 'clove') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'čenova', 'clove';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('čenova')
     and unit_code <> 'clove' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'čenova', 'clove', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('clove')
                   and unit_code = 'clove') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'clove', 'clove';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('clove')
     and unit_code <> 'clove' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'clove', 'clove', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('cloves')
                   and unit_code = 'clove') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'cloves', 'clove';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('cloves')
     and unit_code <> 'clove' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'cloves', 'clove', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('glavica')
                   and unit_code = 'head') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'glavica', 'head';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('glavica')
     and unit_code <> 'head' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'glavica', 'head', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('glavice')
                   and unit_code = 'head') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'glavice', 'head';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('glavice')
     and unit_code <> 'head' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'glavice', 'head', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('head')
                   and unit_code = 'head') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'head', 'head';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('head')
     and unit_code <> 'head' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'head', 'head', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('veza')
                   and unit_code = 'bunch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'veza', 'bunch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('veza')
     and unit_code <> 'bunch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'veza', 'bunch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('struk')
                   and unit_code = 'bunch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'struk', 'bunch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('struk')
     and unit_code <> 'bunch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'struk', 'bunch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('bunch')
                   and unit_code = 'bunch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'bunch', 'bunch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('bunch')
     and unit_code <> 'bunch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'bunch', 'bunch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kriška')
                   and unit_code = 'slice') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kriška', 'slice';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kriška')
     and unit_code <> 'slice' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kriška', 'slice', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kriške')
                   and unit_code = 'slice') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kriške', 'slice';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kriške')
     and unit_code <> 'slice' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kriške', 'slice', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('parče')
                   and unit_code = 'slice') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'parče', 'slice';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('parče')
     and unit_code <> 'slice' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'parče', 'slice', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('slice')
                   and unit_code = 'slice') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'slice', 'slice';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('slice')
     and unit_code <> 'slice' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'slice', 'slice', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kesica')
                   and unit_code = 'sachet') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kesica', 'sachet';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kesica')
     and unit_code <> 'sachet' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kesica', 'sachet', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('kesice')
                   and unit_code = 'sachet') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'kesice', 'sachet';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('kesice')
     and unit_code <> 'sachet' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'kesice', 'sachet', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('sachet')
                   and unit_code = 'sachet') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'sachet', 'sachet';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('sachet')
     and unit_code <> 'sachet' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'sachet', 'sachet', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('konzerva')
                   and unit_code = 'can') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'konzerva', 'can';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('konzerva')
     and unit_code <> 'can' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'konzerva', 'can', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('can')
                   and unit_code = 'can') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'can', 'can';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('can')
     and unit_code <> 'can' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'can', 'can', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('prstohvat')
                   and unit_code = 'pinch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'prstohvat', 'pinch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('prstohvat')
     and unit_code <> 'pinch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'prstohvat', 'pinch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('prstohvata')
                   and unit_code = 'pinch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'prstohvata', 'pinch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('prstohvata')
     and unit_code <> 'pinch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'prstohvata', 'pinch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('pinch')
                   and unit_code = 'pinch') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'pinch', 'pinch';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('pinch')
     and unit_code <> 'pinch' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'pinch', 'pinch', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('po ukusu')
                   and unit_code = 'to_taste') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'po ukusu', 'to_taste';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('po ukusu')
     and unit_code <> 'to_taste' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'po ukusu', 'to_taste', other;
  end if;

  if not exists (select 1 from unit_names
                 where normalized_name = normalize_text('to taste')
                   and unit_code = 'to_taste') then
    failures := failures + 1;
    raise warning 'unit alias % is not seeded as %', 'to taste', 'to_taste';
  end if;

  select unit_code into other from unit_names
   where normalized_name = normalize_text('to taste')
     and unit_code <> 'to_taste' limit 1;
  if other is not null then
    failures := failures + 1;
    raise warning 'unit alias % resolves to both % and %', 'to taste', 'to_taste', other;
  end if;

  if failures > 0 then
    raise exception '% unit alias check(s) failed. The parser fixture and unit_names disagree.', failures;
  end if;

  raise notice 'unit aliases: 67 pair(s) passed';
end
$$;
