// Generates the Postgres half of the display-name-chain contract from the
// same fixture the Dart test (test/features/ingredients/
// display_name_chain_test.dart) reads (CLAUDE.md rule 6, D72).
//
// Postgres cannot read test/fixtures/display_names.json itself, and hand-
// maintaining a second copy of the cases is exactly the drift the shared
// fixture exists to prevent. So the .sql is generated and committed, and
// `make test-sql` regenerates it before running.
//
// Each case gets its own throwaway ingredient row (no `key`, so the seed's
// own upserts can never collide with it) and its own ingredient_names rows,
// all household_id null -- ingredient_display_name() only ever considers
// global rows. Both are deleted at the end of the case, so the file is safe
// to re-run against a database that already has one.
//
// Usage: dart run tool/gen_display_name_sql.dart

import 'dart:convert';
import 'dart:io';

const String _fixturePath = 'test/fixtures/display_names.json';
const String _outputPath = 'supabase/tests/display_names_test.sql';

void main() {
  final File fixture = File(_fixturePath);
  if (!fixture.existsSync()) {
    stderr.writeln('gen_display_name_sql: missing $_fixturePath');
    exit(1);
  }

  final List<dynamic> cases =
      jsonDecode(fixture.readAsStringSync()) as List<dynamic>;

  final StringBuffer out = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_display_name_sql.dart -- DO NOT EDIT.')
    ..writeln('-- Source of truth: $_fixturePath')
    ..writeln('--')
    ..writeln('-- Asserts that ingredient_display_name() in Postgres agrees')
    ..writeln('-- with DisplayNameChain in Dart on every fixture case (D72).')
    ..writeln('-- Raises on the first disagreement.')
    ..writeln('--')
    ..writeln('-- Run: make test-sql')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  test_id  uuid;')
    ..writeln('  actual   text;')
    ..writeln('  failures int := 0;')
    ..writeln('begin');

  for (final dynamic entry in cases) {
    final Map<String, dynamic> c = entry as Map<String, dynamic>;
    final String description = c['description'] as String;
    final String loc = _quote(c['locale'] as String);
    final List<Map<String, dynamic>> names =
        (c['names'] as List<dynamic>).cast<Map<String, dynamic>>();
    final String? expected = c['expected'] as String?;
    final String expectedSql = expected == null ? 'null' : _quote(expected);

    out
      ..writeln('  -- ${description.replaceAll('\n', ' ')}')
      ..writeln('  insert into ingredients default values')
      ..writeln('  returning id into test_id;');

    for (final Map<String, dynamic> n in names) {
      out
        ..writeln('  insert into ingredient_names')
        ..writeln('    (ingredient_id, name, locale, is_display_name, source, created_at)')
        ..writeln('  values')
        ..writeln(
          '    (test_id, ${_quote(n['name'] as String)}, ${_quote(n['locale'] as String)}, '
          '${n['is_display_name']}, \'curated\', ${_quote(n['created_at'] as String)}::timestamptz);',
        );
    }

    out
      ..writeln('  select ingredient_display_name(test_id, $loc) into actual;')
      ..writeln('  if actual is distinct from $expectedSql then')
      ..writeln('    failures := failures + 1;')
      ..writeln("    raise warning 'display_names: % -- got %, expected %',")
      ..writeln('      ${_quote(description)}, actual, $expectedSql;')
      ..writeln('  end if;')
      ..writeln('  delete from ingredient_names where ingredient_id = test_id;')
      ..writeln('  delete from ingredients where id = test_id;')
      ..writeln();
  }

  out
    ..writeln('  if failures > 0 then')
    ..writeln("    raise exception '% display-name case(s) failed. Postgres "
        "ingredient_display_name() and Dart DisplayNameChain disagree.', "
        'failures;')
    ..writeln('  end if;')
    ..writeln()
    ..writeln("  raise notice 'display_names: ${cases.length} case(s) passed';")
    ..writeln('end')
    ..writeln(r'$$;');

  File(_outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(out.toString());

  stdout.writeln(
      'gen_display_name_sql: wrote $_outputPath (${cases.length} cases)');
}

/// Renders a Dart string as a SQL literal, escaping embedded quotes and using
/// an E'' string when the value contains characters that need escapes.
String _quote(String value) {
  final String escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", "''")
      .replaceAll('\t', r'\t')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r');
  final bool needsEscapeString =
      value.contains('\t') || value.contains('\n') || value.contains('\r') ||
          value.contains(r'\');
  return needsEscapeString ? "E'$escaped'" : "'$escaped'";
}
