// Generates the Postgres half of the normalization contract from the same
// fixture the Dart test reads (CLAUDE.md rule 6, D5).
//
// Postgres cannot read test/fixtures/normalization.json itself, and hand-
// maintaining a second copy of the cases is exactly the drift the shared
// fixture exists to prevent. So the .sql is generated and committed, and
// `make test-sql` regenerates it before running.
//
// Usage: dart run tool/gen_normalization_sql.dart

import 'dart:convert';
import 'dart:io';

const String _fixturePath = 'test/fixtures/normalization.json';
const String _outputPath = 'supabase/tests/normalization_test.sql';

void main() {
  final File fixture = File(_fixturePath);
  if (!fixture.existsSync()) {
    stderr.writeln('gen_normalization_sql: missing $_fixturePath');
    exit(1);
  }

  final List<dynamic> pairs =
      jsonDecode(fixture.readAsStringSync()) as List<dynamic>;

  final StringBuffer out = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_normalization_sql.dart -- DO NOT EDIT.')
    ..writeln('-- Source of truth: $_fixturePath')
    ..writeln('--')
    ..writeln('-- Asserts that normalize_text() in Postgres agrees with')
    ..writeln('-- TextNormalizer in Dart on every fixture case. Raises on the')
    ..writeln('-- first disagreement.')
    ..writeln('--')
    ..writeln('-- Run: make test-sql')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  failures int := 0;')
    ..writeln('  actual   text;')
    ..writeln('begin');

  for (final dynamic entry in pairs) {
    final List<dynamic> pair = entry as List<dynamic>;
    final String input = _quote(pair[0] as String);
    final String expected = _quote(pair[1] as String);

    out
      ..writeln('  actual := normalize_text($input);')
      ..writeln('  if actual is distinct from $expected then')
      ..writeln('    failures := failures + 1;')
      ..writeln("    raise warning 'normalize_text(%) = %, expected %',")
      ..writeln('      $input, actual, $expected;')
      ..writeln('  end if;');
  }

  out
    ..writeln()
    ..writeln('  if failures > 0 then')
    ..writeln("    raise exception '% normalization case(s) failed. Postgres "
        "normalize_text() and Dart TextNormalizer disagree.', failures;")
    ..writeln('  end if;')
    ..writeln()
    ..writeln("  raise notice 'normalization: ${pairs.length} case(s) passed';")
    ..writeln('end')
    ..writeln(r'$$;');

  File(_outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(out.toString());

  stdout.writeln(
      'gen_normalization_sql: wrote $_outputPath (${pairs.length} cases)');
}

/// Renders a Dart string as a SQL literal, escaping embedded quotes and using
/// an E'' string when the value contains characters that need escapes.
String _quote(String value) {
  final String escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", "''")
      .replaceAll('\t', r'\t')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r');
  final bool needsEscapeString =
      value.contains('\t') || value.contains('\n') || value.contains('\r') ||
          value.contains(r'\');
  return needsEscapeString ? "E'$escaped'" : "'$escaped'";
}
