// Turns the catalog seed CSVs into a migration (D29).
//
// Usage:
//   dart run tool/gen_ingredient_seed.dart              # --check
//   dart run tool/gen_ingredient_seed.dart --check
//   dart run tool/gen_ingredient_seed.dart --new-migration
//
// WHY A MIGRATION AND NOT supabase/seed.sql
//
// [db.seed] in supabase/config.toml runs on a local `db reset` and nowhere
// else. The curated catalog is not fixture data -- it is reference data the
// matcher depends on in production, so it has to travel through the only thing
// `supabase db push` executes. See the comment in config.toml.
//
// WHY A NEW FILE EVERY TIME
//
// CLAUDE.md: never edit an applied migration. So editing the CSVs cannot
// rewrite the SQL in place the way tool/gen_normalization_sql.dart does. Each
// regeneration emits a NEW timestamped migration holding the full upsert of
// the current CSV state. Every emitted file is idempotent, so applying v1 then
// v2 converges on v2, and `supabase db reset` replaying all of them is correct
// (just slightly redundant). No file is ever edited.
//
// WHY --check EXISTS
//
// gen_normalization_sql.dart cannot drift: `make test-sql` regenerates its
// output in place before every run. This generator cannot do that, so drift --
// a CSV edited with no migration emitted -- is the *default* failure mode
// unless something checks. --check is that something, and `make check` runs it.
//
// DELETIONS ARE NOT GENERATED, ON PURPOSE
//
// A key that disappears from the CSV is left alone. The generator cannot tell
// "retired" from "typo", and retiring a curated ingredient means repointing
// every recipe that used it -- that is merge_ingredients(), a reviewed act,
// never a side effect of editing a spreadsheet.

import 'dart:io';

import 'seed_csv.dart';

const String _migrationsDir = 'supabase/migrations';
const String _suffix = '_ingredient_catalog_seed.sql';

void main(List<String> args) {
  final bool emit = args.contains('--new-migration');
  if (!emit && args.isNotEmpty && !args.contains('--check')) {
    stderr.writeln('gen_ingredient_seed: unknown argument ${args.first}');
    exit(2);
  }

  final SeedCatalog catalog = readCatalog();

  final List<SeedProblem> problems = validate(catalog);
  if (problems.isNotEmpty) {
    stderr.writeln('gen_ingredient_seed: the seed CSVs are not valid.');
    for (final SeedProblem p in problems) {
      stderr.writeln('  $p');
    }
    exit(1);
  }

  final String fingerprint = catalogFingerprint();
  final File? newest = _newestSeedMigration();
  final String? applied =
      newest == null ? null : _fingerprintOf(newest.readAsStringSync());

  if (applied == fingerprint) {
    stdout.writeln('gen_ingredient_seed: catalog unchanged '
        '(${catalog.ingredients.length} ingredients, '
        '${catalog.names.length} names).');
    return;
  }

  if (!emit) {
    stderr
      ..writeln('gen_ingredient_seed: the seed CSVs have changed since '
          '${newest?.path ?? "(no seed migration yet)"}.')
      ..writeln('Run `make seed` to emit a new migration.');
    exit(1);
  }

  final String stamp = _timestamp(DateTime.now().toUtc());
  final File out = File('$_migrationsDir/$stamp$_suffix');
  out.writeAsStringSync(_render(catalog, fingerprint, stamp));

  stdout.writeln('gen_ingredient_seed: wrote ${out.path} '
      '(${catalog.ingredients.length} ingredients, '
      '${catalog.names.length} names)');
}

String _render(SeedCatalog catalog, String fingerprint, String stamp) {
  final StringBuffer out = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_ingredient_seed.dart -- DO NOT EDIT.')
    ..writeln('-- Source of truth: $ingredientsPath')
    ..writeln('--                  $namesPath')
    ..writeln('-- source-fingerprint: $fingerprint')
    ..writeln('--')
    ..writeln('-- The curated ingredient core (D1, D29). Regenerate with')
    ..writeln('-- `make seed` after editing either CSV; that emits a NEW')
    ..writeln('-- migration rather than rewriting this one, which is applied.')
    ..writeln('--')
    ..writeln('-- Every statement here is an upsert, so this file is safe to')
    ..writeln('-- re-run and safe to apply after a later regeneration of the')
    ..writeln('-- same catalog. Two guards make that true:')
    ..writeln('--')
    ..writeln('--   * `where ... is distinct from ...` on the upserts. Without')
    ..writeln('--     it every deploy would touch updated_at on all')
    ..writeln('--     ${catalog.ingredients.length} rows, and Phase 2\'s delta fetch')
    ..writeln('--     (updated_at > last_sync_at) would re-download the whole')
    ..writeln('--     catalog to every device for a no-op release. It reads')
    ..writeln('--     like a micro-optimisation and is actually the difference')
    ..writeln('--     between a working cache and a broken one.')
    ..writeln('--')
    ..writeln('--   * `deleted_at is null` on every join. A curated ingredient')
    ..writeln('--     that was merged away stays merged away; re-running the')
    ..writeln('--     seed must never resurrect it or re-attach names to a')
    ..writeln('--     tombstone.')
    ..writeln();

  // ---- 1. ingredients ------------------------------------------------------
  out
    ..writeln('-- 1. The concept rows. Parents are left null here and resolved')
    ..writeln('--    in pass 2, so the CSV may list a child before its parent.')
    ..writeln('insert into ingredients as i')
    ..writeln('  (key, category, default_unit_family, is_pantry_staple, is_verified)')
    ..writeln('values');

  final List<String> ingRows = <String>[
    for (final SeedIngredient i in catalog.ingredients)
      '  (${_lit(i.key)}, ${_lit(i.category)}, ${_lit(i.defaultUnitFamily)}, '
          '${i.isPantryStaple}, true)',
  ];
  out
    ..writeln(ingRows.join(',\n'))
    ..writeln('on conflict (key) do update set')
    ..writeln('  category            = excluded.category,')
    ..writeln('  default_unit_family = excluded.default_unit_family,')
    ..writeln('  is_pantry_staple    = excluded.is_pantry_staple,')
    ..writeln('  is_verified         = true')
    ..writeln('where i.deleted_at is null')
    ..writeln('  and (i.category, i.default_unit_family, i.is_pantry_staple, '
        'i.is_verified)')
    ..writeln('      is distinct from')
    ..writeln('      (excluded.category, excluded.default_unit_family,')
    ..writeln('       excluded.is_pantry_staple, true);')
    ..writeln();

  // ---- 2. parents ----------------------------------------------------------
  final Map<String, String> links = catalog.parentLinks;
  out
    ..writeln('-- 2. Parent links (D3, one level). Every key now exists, so')
    ..writeln('--    CSV ordering does not matter. The one-level rule is')
    ..writeln('--    enforced by a trigger on the table and by validate() in')
    ..writeln('--    tool/seed_csv.dart; this statement just applies it.')
    ..writeln('update ingredients c')
    ..writeln('set parent_id = p.id')
    ..writeln('from ingredients p,')
    ..writeln('     (values');

  final List<MapEntry<String, String>> linkRows = links.entries.toList()
    ..sort((MapEntry<String, String> a, MapEntry<String, String> b) =>
        a.key.compareTo(b.key));
  out
    ..writeln(<String>[
      for (int n = 0; n < linkRows.length; n++)
        '       (${_lit(linkRows[n].key)}${n == 0 ? "::text" : ""}, '
            '${_lit(linkRows[n].value)}${n == 0 ? "::text" : ""})',
    ].join(',\n'))
    ..writeln('     ) as m(child_key, parent_key)')
    ..writeln('where c.key = m.child_key')
    ..writeln('  and p.key = m.parent_key')
    ..writeln('  and c.deleted_at is null')
    ..writeln('  and p.deleted_at is null')
    ..writeln('  and c.parent_id is distinct from p.id;')
    ..writeln();

  // ---- 3. demote replaced display names -----------------------------------
  final List<SeedName> displays =
      catalog.names.where((SeedName n) => n.isDisplayName).toList();
  out
    ..writeln('-- 3. Demote a display name the CSV has replaced.')
    ..writeln('--')
    ..writeln('--    one_display_name_per_locale is a unique index, and step 4')
    ..writeln('--    infers conflicts against a DIFFERENT one. So renaming a')
    ..writeln('--    display name in the CSV would raise a unique violation')
    ..writeln('--    that no ON CONFLICT clause catches, unless the old row is')
    ..writeln('--    demoted first. It keeps its row and stays matchable -- it')
    ..writeln('--    simply stops being the name shown back.')
    ..writeln('update ingredient_names n')
    ..writeln('set is_display_name = false')
    ..writeln('from ingredients i,')
    ..writeln('     (values');
  out
    ..writeln(<String>[
      for (int n = 0; n < displays.length; n++)
        '       (${_lit(displays[n].ingredientKey)}${n == 0 ? "::text" : ""}, '
            '${_lit(displays[n].locale)}${n == 0 ? "::text" : ""}, '
            '${_lit(displays[n].name)}${n == 0 ? "::text" : ""})',
    ].join(',\n'))
    ..writeln('     ) as v(ingredient_key, locale, name)')
    ..writeln('where i.key = v.ingredient_key')
    ..writeln('  and i.deleted_at is null')
    ..writeln('  and n.ingredient_id = i.id')
    ..writeln('  and n.locale = v.locale')
    ..writeln('  and n.household_id is null')
    ..writeln('  and n.deleted_at is null')
    ..writeln('  and n.is_display_name')
    ..writeln('  and n.normalized_name is distinct from normalize_text(v.name);')
    ..writeln();

  // ---- 4. names ------------------------------------------------------------
  out
    ..writeln('-- 4. The names. `source = curated` marks these as hand-written')
    ..writeln('--    rather than produced by the matcher, and household_id is')
    ..writeln('--    null because the catalog is global -- an alias learned')
    ..writeln('--    once resolves for every household (docs/INGREDIENTS.md).')
    ..writeln('--')
    ..writeln('--    The conflict target is spelled out rather than named:')
    ..writeln('--    ingredient_names_unique is a unique INDEX over an')
    ..writeln('--    expression, not a table constraint, so')
    ..writeln('--    `on conflict on constraint ...` does not compile against')
    ..writeln('--    it. normalized_name is a generated column, which may')
    ..writeln('--    appear in the inference list but not in the insert list.')
    ..writeln('insert into ingredient_names as n')
    ..writeln('  (ingredient_id, name, locale, is_display_name, household_id, source)')
    ..writeln('select i.id, v.name, v.locale, v.is_display_name, null, \'curated\'')
    ..writeln('from (values');
  out
    ..writeln(<String>[
      for (int n = 0; n < catalog.names.length; n++)
        '       (${_lit(catalog.names[n].ingredientKey)}${n == 0 ? "::text" : ""}, '
            '${_lit(catalog.names[n].name)}${n == 0 ? "::text" : ""}, '
            '${_lit(catalog.names[n].locale)}${n == 0 ? "::text" : ""}, '
            '${catalog.names[n].isDisplayName})',
    ].join(',\n'))
    ..writeln('     ) as v(ingredient_key, name, locale, is_display_name)')
    ..writeln('join ingredients i')
    ..writeln('  on i.key = v.ingredient_key and i.deleted_at is null')
    ..writeln('on conflict (normalized_name, locale,')
    ..writeln('             coalesce(household_id, '
        '\'00000000-0000-0000-0000-000000000000\'::uuid))')
    ..writeln('do update set')
    ..writeln('  ingredient_id   = excluded.ingredient_id,')
    ..writeln('  is_display_name = excluded.is_display_name,')
    ..writeln('  source          = excluded.source,')
    ..writeln('  deleted_at      = null')
    ..writeln('where n.ingredient_id   is distinct from excluded.ingredient_id')
    ..writeln('   or n.is_display_name is distinct from excluded.is_display_name')
    ..writeln('   or n.deleted_at is not null;')
    ..writeln();

  // ---- 5. verify -----------------------------------------------------------
  out
    ..writeln('-- 5. Fail loudly rather than leaving a half-seeded catalog. A')
    ..writeln('--    key missing here means step 1 silently skipped a row,')
    ..writeln('--    which the upsert guard makes possible if a row is already')
    ..writeln('--    present and soft-deleted.')
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  n_ing   int;')
    ..writeln('  n_name  int;')
    ..writeln('  missing int;')
    ..writeln('begin')
    ..writeln('  select count(*) into n_ing from ingredients where key is not null;')
    ..writeln('  select count(*) into n_name from ingredient_names')
    ..writeln("   where source = 'curated' and deleted_at is null;")
    ..writeln()
    ..writeln('  select count(*) into missing')
    ..writeln('  from (values')
    ..writeln(<String>[
      for (int n = 0; n < catalog.ingredients.length; n++)
        '         (${_lit(catalog.ingredients[n].key)}'
            '${n == 0 ? "::text" : ""})',
    ].join(',\n'))
    ..writeln('       ) as v(key)')
    ..writeln('  where not exists (select 1 from ingredients i '
        'where i.key = v.key);')
    ..writeln()
    ..writeln('  if missing > 0 then')
    ..writeln("    raise exception 'catalog seed: % curated key(s) missing "
        "after seeding', missing;")
    ..writeln('  end if;')
    ..writeln()
    ..writeln("  raise notice 'catalog seed: % keyed ingredient(s), "
        "% curated name(s)', n_ing, n_name;")
    ..writeln('end')
    ..writeln(r'$$;');

  return out.toString();
}

/// Renders a Dart string as a SQL literal. Null becomes an untyped `null`,
/// which the target column types resolve.
String _lit(String? value) {
  if (value == null) return 'null';
  return "'${value.replaceAll("'", "''")}'";
}

File? _newestSeedMigration() {
  final Directory dir = Directory(_migrationsDir);
  if (!dir.existsSync()) return null;

  final List<File> found = dir
      .listSync()
      .whereType<File>()
      .where((File f) => f.path.endsWith(_suffix))
      .toList()
    ..sort((File a, File b) => a.path.compareTo(b.path));

  return found.isEmpty ? null : found.last;
}

String? _fingerprintOf(String sql) {
  for (final String line in sql.split('\n').take(10)) {
    const String marker = '-- source-fingerprint:';
    if (line.startsWith(marker)) {
      return line.substring(marker.length).trim();
    }
  }
  return null;
}

String _timestamp(DateTime t) =>
    '${t.year.toString().padLeft(4, '0')}'
    '${t.month.toString().padLeft(2, '0')}'
    '${t.day.toString().padLeft(2, '0')}'
    '${t.hour.toString().padLeft(2, '0')}'
    '${t.minute.toString().padLeft(2, '0')}'
    '${t.second.toString().padLeft(2, '0')}';
