// Generates the Postgres half of the unit alias contract from the same fixture
// the Dart parser tests read.
//
// Same shape and same reason as tool/gen_normalization_sql.dart: Postgres
// cannot read test/fixtures/unit_aliases.json, and hand-maintaining a second
// copy of the pairs is exactly the drift a shared fixture exists to prevent.
// The .sql is generated and committed, and `make test-sql` regenerates it
// before running.
//
// What it protects: the parser recognises `kašike` and writes unit_code
// 'tbsp'. If the migration seeding unit_names ever loses that alias, or points
// it at a different unit, the parser keeps producing a code the catalog no
// longer justifies. The failure would surface much later, in Phase 1c, as a
// foreign key violation on recipe_ingredients.unit_code.
//
// Usage: dart run tool/gen_unit_alias_sql.dart

import 'dart:convert';
import 'dart:io';

const String _fixturePath = 'test/fixtures/unit_aliases.json';
const String _outputPath = 'supabase/tests/unit_alias_test.sql';

void main() {
  final File fixture = File(_fixturePath);
  if (!fixture.existsSync()) {
    stderr.writeln('gen_unit_alias_sql: missing $_fixturePath');
    exit(1);
  }

  final Map<String, dynamic> raw =
      jsonDecode(fixture.readAsStringSync()) as Map<String, dynamic>;

  // `_comment` carries the fixture's own documentation and is not a pair.
  final Map<String, String> aliases = <String, String>{
    for (final MapEntry<String, dynamic> e in raw.entries)
      if (!e.key.startsWith('_')) e.key: e.value as String,
  };

  final StringBuffer out = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_unit_alias_sql.dart -- DO NOT EDIT.')
    ..writeln('-- Source of truth: $_fixturePath')
    ..writeln('--')
    ..writeln('-- Asserts that every unit spelling the Dart line parser is')
    ..writeln('-- expected to recognise exists in unit_names and resolves to')
    ..writeln('-- exactly one unit. Two checks per alias: that the pair is')
    ..writeln('-- present, and that no OTHER unit also claims the spelling --')
    ..writeln('-- an alias meaning two things would have the parser silently')
    ..writeln('-- pick whichever row came back first.')
    ..writeln('--')
    ..writeln('-- Run: make test-sql')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  failures int := 0;')
    ..writeln('  other    text;')
    ..writeln('begin');

  for (final MapEntry<String, String> alias in aliases.entries) {
    final String name = _quote(alias.key);
    final String code = _quote(alias.value);

    out
      ..writeln('  if not exists (select 1 from unit_names')
      ..writeln('                 where normalized_name = normalize_text($name)')
      ..writeln('                   and unit_code = $code) then')
      ..writeln('    failures := failures + 1;')
      ..writeln("    raise warning 'unit alias % is not seeded as %', "
          '$name, $code;')
      ..writeln('  end if;')
      ..writeln()
      ..writeln('  select unit_code into other from unit_names')
      ..writeln('   where normalized_name = normalize_text($name)')
      ..writeln('     and unit_code <> $code limit 1;')
      ..writeln('  if other is not null then')
      ..writeln('    failures := failures + 1;')
      ..writeln("    raise warning 'unit alias % resolves to both % and %', "
          '$name, $code, other;')
      ..writeln('  end if;')
      ..writeln();
  }

  out
    ..writeln('  if failures > 0 then')
    ..writeln("    raise exception '% unit alias check(s) failed. The parser "
        "fixture and unit_names disagree.', failures;")
    ..writeln('  end if;')
    ..writeln()
    ..writeln("  raise notice 'unit aliases: ${aliases.length} "
        "pair(s) passed';")
    ..writeln('end')
    ..writeln(r'$$;');

  File(_outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(out.toString());

  stdout.writeln(
      'gen_unit_alias_sql: wrote $_outputPath (${aliases.length} pairs)');
}

/// Renders a Dart string as a SQL literal. Every key in the fixture is a plain
/// word or two, so only the quote case can actually arise -- handled anyway.
String _quote(String value) => "'${value.replaceAll("'", "''")}'";
